# Generated by Django 3.1.5 on 2021-03-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_tip', models.CharField(max_length=280)),
                ('posted_by', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('retweets', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_link', to='pages.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tips',
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_id_collection', to='pages.tip'),
        ),
    ]
