# Generated by Django 3.1.5 on 2021-03-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='tip_id',
            new_name='tip',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='links',
        ),
    ]
