# Generated by Django 3.1.5 on 2021-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210303_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='python_tip',
            field=models.TextField(blank=True),
        ),
    ]
