# Generated by Django 3.1.5 on 2021-03-04 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210304_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
