# Generated by Django 3.1.5 on 2021-03-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_tip_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.tip'),
        ),
        migrations.AlterField(
            model_name='link',
            name='tweet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
