# Generated by Django 3.1.5 on 2021-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_tip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
