# Generated by Django 3.1.5 on 2021-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210308_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
