# Generated by Django 3.1.5 on 2021-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210308_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='posted_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
